# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tempreature', models.IntegerField()),
                ('ChemicalComposition', models.CharField(max_length=200)),
                ('RockType', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WellInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberOfEstablishedPlantsNearby', models.IntegerField()),
                ('NumberOfDevelopmentalPlantsNearby', models.IntegerField()),
                ('OperatorName', models.CharField(max_length=200)),
                ('WellStatus', models.CharField(max_length=200)),
                ('ConversionTechnology', models.CharField(max_length=200)),
                ('CoolingType', models.CharField(max_length=200)),
                ('AgeOfWellInYears', models.IntegerField()),
                ('WellDepthInMeters', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WellInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(choices=[('US', 'United States of America'), ('UK', 'United Kingdon')], max_length=200)),
                ('State', models.CharField(choices=[('US', 'United States of America'), ('UK', 'United Kingdon')], max_length=200)),
                ('City', models.CharField(choices=[('US', 'United States of America'), ('UK', 'United Kingdon')], max_length=200)),
                ('Well', models.CharField(choices=[('US', 'United States of America'), ('UK', 'United Kingdon')], max_length=200)),
            ],
        ),
    ]
