# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170801_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskprofile',
            name='Notes',
            field=models.CharField(max_length=1000),
        ),
    ]
