# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170801_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellinstance',
            name='City',
            field=models.CharField(choices=[('CA', 'California'), ('LA', 'Lassen')], max_length=200),
        ),
        migrations.AlterField(
            model_name='wellinstance',
            name='Country',
            field=models.CharField(choices=[('US', 'United States of America'), ('IN', 'Indonesia')], max_length=200),
        ),
        migrations.AlterField(
            model_name='wellinstance',
            name='State',
            field=models.CharField(choices=[('CA', 'California'), ('NY', 'New York')], max_length=200),
        ),
        migrations.AlterField(
            model_name='wellinstance',
            name='Well',
            field=models.CharField(choices=[('S3', 'Sinclair 3'), ('KH', 'Kellog Hot Spring')], max_length=200),
        ),
    ]
