# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170803_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoinfo',
            old_name='ChemicalComposition',
            new_name='CO2',
        ),
        migrations.RenameField(
            model_name='geoinfo',
            old_name='RockType',
            new_name='Ph',
        ),
    ]
